// <auto-generated />
using System;
using Archieve.DataAccess.DataConfigration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Archieve.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200912235117_13092020")]
    partial class _13092020
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Archieve.DatabaseLayer.Models.Classification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClassificationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsertUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Classifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassificationName = "ترقين قيد ",
                            InsertDate = new DateTime(2020, 9, 13, 2, 51, 15, 651, DateTimeKind.Local).AddTicks(1269),
                            IsDeleted = false,
                            UpdatedDate = new DateTime(2020, 9, 13, 2, 51, 15, 651, DateTimeKind.Local).AddTicks(2426)
                        },
                        new
                        {
                            Id = 2,
                            ClassificationName = " طلب اجازة",
                            InsertDate = new DateTime(2020, 9, 13, 2, 51, 15, 651, DateTimeKind.Local).AddTicks(3812),
                            IsDeleted = false,
                            UpdatedDate = new DateTime(2020, 9, 13, 2, 51, 15, 651, DateTimeKind.Local).AddTicks(3859)
                        },
                        new
                        {
                            Id = 3,
                            ClassificationName = " طلب صيانة",
                            InsertDate = new DateTime(2020, 9, 13, 2, 51, 15, 651, DateTimeKind.Local).AddTicks(3896),
                            IsDeleted = false,
                            UpdatedDate = new DateTime(2020, 9, 13, 2, 51, 15, 651, DateTimeKind.Local).AddTicks(3904)
                        },
                        new
                        {
                            Id = 4,
                            ClassificationName = " اوامر ادارية",
                            InsertDate = new DateTime(2020, 9, 13, 2, 51, 15, 651, DateTimeKind.Local).AddTicks(3916),
                            IsDeleted = false,
                            UpdatedDate = new DateTime(2020, 9, 13, 2, 51, 15, 651, DateTimeKind.Local).AddTicks(3923)
                        });
                });

            modelBuilder.Entity("Archieve.DatabaseLayer.Models.Employee", b =>
                {
                    b.Property<int>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FinID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsertUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("EmpId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Archieve.DatabaseLayer.Models.ImageArchive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("ContentMail")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Extension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FK_MailArchiveID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsertUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FK_MailArchiveID");

                    b.ToTable("ImageArchives");
                });

            modelBuilder.Entity("Archieve.DatabaseLayer.Models.MailArchive", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("ArchiveDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FK_ClassificationId")
                        .HasColumnType("int");

                    b.Property<int?>("FK_FromJehazId")
                        .HasColumnType("int");

                    b.Property<int?>("FK_MailTypeId")
                        .HasColumnType("int");

                    b.Property<int>("FK_PostTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("FK_SecurityId")
                        .HasColumnType("int");

                    b.Property<int>("FK_StatusId")
                        .HasColumnType("int");

                    b.Property<int?>("FK_ToJehazId")
                        .HasColumnType("int");

                    b.Property<string>("FK_User")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsertUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MailId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Topic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserWorkPlaceID")
                        .HasColumnType("int");

                    b.Property<string>("Year")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("FK_ClassificationId");

                    b.HasIndex("FK_FromJehazId");

                    b.HasIndex("FK_MailTypeId");

                    b.HasIndex("FK_PostTypeId");

                    b.HasIndex("FK_SecurityId");

                    b.HasIndex("FK_StatusId");

                    b.HasIndex("FK_ToJehazId");

                    b.HasIndex("FK_User");

                    b.HasIndex("UserWorkPlaceID");

                    b.ToTable("MailArchives");
                });

            modelBuilder.Entity("Archieve.DatabaseLayer.Models.MailType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsertUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MailName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MailTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InsertDate = new DateTime(2020, 9, 13, 2, 51, 15, 646, DateTimeKind.Local).AddTicks(379),
                            IsDeleted = false,
                            MailName = "داخي",
                            UpdatedDate = new DateTime(2020, 9, 13, 2, 51, 15, 646, DateTimeKind.Local).AddTicks(1645)
                        },
                        new
                        {
                            Id = 2,
                            InsertDate = new DateTime(2020, 9, 13, 2, 51, 15, 648, DateTimeKind.Local).AddTicks(7512),
                            IsDeleted = false,
                            MailName = "خارجي",
                            UpdatedDate = new DateTime(2020, 9, 13, 2, 51, 15, 648, DateTimeKind.Local).AddTicks(7537)
                        });
                });

            modelBuilder.Entity("Archieve.DatabaseLayer.Models.MangerDepartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsertUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("WorkPlaceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkPlaceId");

                    b.ToTable("MangerDepartment");
                });

            modelBuilder.Entity("Archieve.DatabaseLayer.Models.PostType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsertUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PostName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PostTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InsertDate = new DateTime(2020, 9, 13, 2, 51, 15, 652, DateTimeKind.Local).AddTicks(3043),
                            IsDeleted = false,
                            PostName = "صادر",
                            UpdatedDate = new DateTime(2020, 9, 13, 2, 51, 15, 652, DateTimeKind.Local).AddTicks(3079)
                        },
                        new
                        {
                            Id = 2,
                            InsertDate = new DateTime(2020, 9, 13, 2, 51, 15, 652, DateTimeKind.Local).AddTicks(3446),
                            IsDeleted = false,
                            PostName = "وارد",
                            UpdatedDate = new DateTime(2020, 9, 13, 2, 51, 15, 652, DateTimeKind.Local).AddTicks(3454)
                        });
                });

            modelBuilder.Entity("Archieve.DatabaseLayer.Models.Security", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsertUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Securities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InsertDate = new DateTime(2020, 9, 13, 2, 51, 15, 649, DateTimeKind.Local).AddTicks(7662),
                            IsDeleted = false,
                            SecurityName = "عادي",
                            UpdatedDate = new DateTime(2020, 9, 13, 2, 51, 15, 649, DateTimeKind.Local).AddTicks(7697)
                        },
                        new
                        {
                            Id = 2,
                            InsertDate = new DateTime(2020, 9, 13, 2, 51, 15, 649, DateTimeKind.Local).AddTicks(8136),
                            IsDeleted = false,
                            SecurityName = "سري",
                            UpdatedDate = new DateTime(2020, 9, 13, 2, 51, 15, 649, DateTimeKind.Local).AddTicks(8145)
                        });
                });

            modelBuilder.Entity("Archieve.DatabaseLayer.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsertUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("StatusName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InsertDate = new DateTime(2020, 9, 13, 2, 51, 15, 653, DateTimeKind.Local).AddTicks(2581),
                            IsDeleted = false,
                            StatusName = "منجر",
                            UpdatedDate = new DateTime(2020, 9, 13, 2, 51, 15, 653, DateTimeKind.Local).AddTicks(2615)
                        },
                        new
                        {
                            Id = 2,
                            InsertDate = new DateTime(2020, 9, 13, 2, 51, 15, 653, DateTimeKind.Local).AddTicks(2975),
                            IsDeleted = false,
                            StatusName = "غير منجر",
                            UpdatedDate = new DateTime(2020, 9, 13, 2, 51, 15, 653, DateTimeKind.Local).AddTicks(2983)
                        });
                });

            modelBuilder.Entity("Archieve.DatabaseLayer.Models.StructureType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsertUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("StructureTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "الجهاز",
                            InsertDate = new DateTime(2020, 9, 13, 2, 51, 15, 656, DateTimeKind.Local).AddTicks(9481),
                            IsDeleted = false,
                            UpdatedDate = new DateTime(2020, 9, 13, 2, 51, 15, 656, DateTimeKind.Local).AddTicks(9520)
                        },
                        new
                        {
                            Id = 2,
                            Description = "الادارة",
                            InsertDate = new DateTime(2020, 9, 13, 2, 51, 15, 656, DateTimeKind.Local).AddTicks(9944),
                            IsDeleted = false,
                            UpdatedDate = new DateTime(2020, 9, 13, 2, 51, 15, 656, DateTimeKind.Local).AddTicks(9953)
                        },
                        new
                        {
                            Id = 3,
                            Description = "دائرة",
                            InsertDate = new DateTime(2020, 9, 13, 2, 51, 15, 656, DateTimeKind.Local).AddTicks(9980),
                            IsDeleted = false,
                            UpdatedDate = new DateTime(2020, 9, 13, 2, 51, 15, 656, DateTimeKind.Local).AddTicks(9987)
                        },
                        new
                        {
                            Id = 4,
                            Description = "قسم",
                            InsertDate = new DateTime(2020, 9, 13, 2, 51, 15, 657, DateTimeKind.Local).AddTicks(5),
                            IsDeleted = false,
                            UpdatedDate = new DateTime(2020, 9, 13, 2, 51, 15, 657, DateTimeKind.Local).AddTicks(13)
                        },
                        new
                        {
                            Id = 5,
                            Description = "وحدة",
                            InsertDate = new DateTime(2020, 9, 13, 2, 51, 15, 657, DateTimeKind.Local).AddTicks(31),
                            IsDeleted = false,
                            UpdatedDate = new DateTime(2020, 9, 13, 2, 51, 15, 657, DateTimeKind.Local).AddTicks(38)
                        },
                        new
                        {
                            Id = 6,
                            Description = "اخرى",
                            InsertDate = new DateTime(2020, 9, 13, 2, 51, 15, 657, DateTimeKind.Local).AddTicks(60),
                            IsDeleted = false,
                            UpdatedDate = new DateTime(2020, 9, 13, 2, 51, 15, 657, DateTimeKind.Local).AddTicks(67)
                        });
                });

            modelBuilder.Entity("Archieve.DatabaseLayer.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("FK_JehazId")
                        .HasColumnType("int");

                    b.Property<int>("FinanceNumber")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FourthName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdentityNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsertUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("MilitaryRank")
                        .HasColumnType("int");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNo")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecondName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThirdName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("FK_JehazId");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Archieve.DatabaseLayer.Models.WorkPlace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FK_WpId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsertUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FK_WpId");

                    b.ToTable("WorkPlaces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FK_WpId = 6,
                            InsertDate = new DateTime(2020, 9, 13, 2, 51, 15, 655, DateTimeKind.Local).AddTicks(2852),
                            IsDeleted = false,
                            ParentId = 0,
                            Text = "عام",
                            UpdatedDate = new DateTime(2020, 9, 13, 2, 51, 15, 655, DateTimeKind.Local).AddTicks(2891)
                        },
                        new
                        {
                            Id = 2,
                            FK_WpId = 1,
                            InsertDate = new DateTime(2020, 9, 13, 2, 51, 15, 655, DateTimeKind.Local).AddTicks(3311),
                            IsDeleted = false,
                            ParentId = 1,
                            Text = "المديرية العامة للعمليات المركزية",
                            UpdatedDate = new DateTime(2020, 9, 13, 2, 51, 15, 655, DateTimeKind.Local).AddTicks(3320)
                        },
                        new
                        {
                            Id = 3,
                            FK_WpId = 6,
                            InsertDate = new DateTime(2020, 9, 13, 2, 51, 15, 655, DateTimeKind.Local).AddTicks(3346),
                            IsDeleted = false,
                            ParentId = 1,
                            Text = "هئيات خارجية",
                            UpdatedDate = new DateTime(2020, 9, 13, 2, 51, 15, 655, DateTimeKind.Local).AddTicks(3353)
                        },
                        new
                        {
                            Id = 4,
                            FK_WpId = 2,
                            InsertDate = new DateTime(2020, 9, 13, 2, 51, 15, 655, DateTimeKind.Local).AddTicks(3373),
                            IsDeleted = false,
                            ParentId = 2,
                            Text = "ادارة الاتصالات",
                            UpdatedDate = new DateTime(2020, 9, 13, 2, 51, 15, 655, DateTimeKind.Local).AddTicks(3380)
                        },
                        new
                        {
                            Id = 5,
                            FK_WpId = 3,
                            InsertDate = new DateTime(2020, 9, 13, 2, 51, 15, 655, DateTimeKind.Local).AddTicks(3399),
                            IsDeleted = false,
                            ParentId = 4,
                            Text = "دائرة نظم المعلومات",
                            UpdatedDate = new DateTime(2020, 9, 13, 2, 51, 15, 655, DateTimeKind.Local).AddTicks(3406)
                        },
                        new
                        {
                            Id = 6,
                            FK_WpId = 4,
                            InsertDate = new DateTime(2020, 9, 13, 2, 51, 15, 655, DateTimeKind.Local).AddTicks(3433),
                            IsDeleted = false,
                            ParentId = 5,
                            Text = "قسم البرمجة",
                            UpdatedDate = new DateTime(2020, 9, 13, 2, 51, 15, 655, DateTimeKind.Local).AddTicks(3440)
                        },
                        new
                        {
                            Id = 7,
                            FK_WpId = 2,
                            InsertDate = new DateTime(2020, 9, 13, 2, 51, 15, 655, DateTimeKind.Local).AddTicks(3459),
                            IsDeleted = false,
                            ParentId = 2,
                            Text = "ادارة الامداد",
                            UpdatedDate = new DateTime(2020, 9, 13, 2, 51, 15, 655, DateTimeKind.Local).AddTicks(3466)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Archieve.DatabaseLayer.Models.ImageArchive", b =>
                {
                    b.HasOne("Archieve.DatabaseLayer.Models.MailArchive", "MailArchive")
                        .WithMany("imageArchives")
                        .HasForeignKey("FK_MailArchiveID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Archieve.DatabaseLayer.Models.MailArchive", b =>
                {
                    b.HasOne("Archieve.DatabaseLayer.Models.Classification", "Classification")
                        .WithMany("mailArchives")
                        .HasForeignKey("FK_ClassificationId");

                    b.HasOne("Archieve.DatabaseLayer.Models.WorkPlace", "FromJehazId")
                        .WithMany("mailArchivesFrom")
                        .HasForeignKey("FK_FromJehazId");

                    b.HasOne("Archieve.DatabaseLayer.Models.MailType", "MailType")
                        .WithMany("mailArchives")
                        .HasForeignKey("FK_MailTypeId");

                    b.HasOne("Archieve.DatabaseLayer.Models.PostType", "PostType")
                        .WithMany("mailArchives")
                        .HasForeignKey("FK_PostTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Archieve.DatabaseLayer.Models.Security", "Security")
                        .WithMany("mailArchives")
                        .HasForeignKey("FK_SecurityId");

                    b.HasOne("Archieve.DatabaseLayer.Models.Status", "Status")
                        .WithMany("mailArchives")
                        .HasForeignKey("FK_StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Archieve.DatabaseLayer.Models.WorkPlace", "ToJehazId")
                        .WithMany("mailArchivesTo")
                        .HasForeignKey("FK_ToJehazId");

                    b.HasOne("Archieve.DatabaseLayer.Models.User", "user")
                        .WithMany("mailArchives")
                        .HasForeignKey("FK_User");

                    b.HasOne("Archieve.DatabaseLayer.Models.WorkPlace", "UserWorkPlace")
                        .WithMany()
                        .HasForeignKey("UserWorkPlaceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Archieve.DatabaseLayer.Models.MangerDepartment", b =>
                {
                    b.HasOne("Archieve.DatabaseLayer.Models.User", "User")
                        .WithMany("MangerDepartment")
                        .HasForeignKey("UserId");

                    b.HasOne("Archieve.DatabaseLayer.Models.WorkPlace", "WorkPlace")
                        .WithMany("MangerDepartment")
                        .HasForeignKey("WorkPlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Archieve.DatabaseLayer.Models.User", b =>
                {
                    b.HasOne("Archieve.DatabaseLayer.Models.WorkPlace", "WorkPlace")
                        .WithMany("Users")
                        .HasForeignKey("FK_JehazId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Archieve.DatabaseLayer.Models.WorkPlace", b =>
                {
                    b.HasOne("Archieve.DatabaseLayer.Models.StructureType", "StructureType")
                        .WithMany("workPlaces")
                        .HasForeignKey("FK_WpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Archieve.DatabaseLayer.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Archieve.DatabaseLayer.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Archieve.DatabaseLayer.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Archieve.DatabaseLayer.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
