// <auto-generated />
using System;
using Archieve.DataAccess.DataConfigration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Archieve.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200913031050_130920200610")]
    partial class _130920200610
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Archieve.DatabaseLayer.Models.Classification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClassificationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsertUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Classifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassificationName = "ترقين قيد ",
                            InsertDate = new DateTime(2020, 9, 13, 6, 10, 49, 604, DateTimeKind.Local).AddTicks(6713),
                            IsDeleted = false,
                            UpdatedDate = new DateTime(2020, 9, 13, 6, 10, 49, 604, DateTimeKind.Local).AddTicks(7480)
                        },
                        new
                        {
                            Id = 2,
                            ClassificationName = " طلب اجازة",
                            InsertDate = new DateTime(2020, 9, 13, 6, 10, 49, 604, DateTimeKind.Local).AddTicks(8435),
                            IsDeleted = false,
                            UpdatedDate = new DateTime(2020, 9, 13, 6, 10, 49, 604, DateTimeKind.Local).AddTicks(8468)
                        },
                        new
                        {
                            Id = 3,
                            ClassificationName = " طلب صيانة",
                            InsertDate = new DateTime(2020, 9, 13, 6, 10, 49, 604, DateTimeKind.Local).AddTicks(8492),
                            IsDeleted = false,
                            UpdatedDate = new DateTime(2020, 9, 13, 6, 10, 49, 604, DateTimeKind.Local).AddTicks(8498)
                        },
                        new
                        {
                            Id = 4,
                            ClassificationName = " اوامر ادارية",
                            InsertDate = new DateTime(2020, 9, 13, 6, 10, 49, 604, DateTimeKind.Local).AddTicks(8506),
                            IsDeleted = false,
                            UpdatedDate = new DateTime(2020, 9, 13, 6, 10, 49, 604, DateTimeKind.Local).AddTicks(8511)
                        });
                });

            modelBuilder.Entity("Archieve.DatabaseLayer.Models.Employee", b =>
                {
                    b.Property<int>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FinID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsertUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("EmpId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Archieve.DatabaseLayer.Models.ImageArchive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("ContentMail")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Extension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FK_MailArchiveID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsertUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FK_MailArchiveID");

                    b.ToTable("ImageArchives");
                });

            modelBuilder.Entity("Archieve.DatabaseLayer.Models.MailArchive", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("ArchiveDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FK_ClassificationId")
                        .HasColumnType("int");

                    b.Property<int?>("FK_FromJehazId")
                        .HasColumnType("int");

                    b.Property<int?>("FK_MailTypeId")
                        .HasColumnType("int");

                    b.Property<int>("FK_PostTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("FK_SecurityId")
                        .HasColumnType("int");

                    b.Property<int>("FK_StatusId")
                        .HasColumnType("int");

                    b.Property<int?>("FK_ToJehazId")
                        .HasColumnType("int");

                    b.Property<string>("FK_User")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsertUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MailId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Topic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserWorkPlaceID")
                        .HasColumnType("int");

                    b.Property<string>("Year")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("FK_ClassificationId");

                    b.HasIndex("FK_FromJehazId");

                    b.HasIndex("FK_MailTypeId");

                    b.HasIndex("FK_PostTypeId");

                    b.HasIndex("FK_SecurityId");

                    b.HasIndex("FK_StatusId");

                    b.HasIndex("FK_ToJehazId");

                    b.HasIndex("FK_User");

                    b.HasIndex("UserWorkPlaceID");

                    b.ToTable("MailArchives");
                });

            modelBuilder.Entity("Archieve.DatabaseLayer.Models.MailType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsertUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MailName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MailTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InsertDate = new DateTime(2020, 9, 13, 6, 10, 49, 600, DateTimeKind.Local).AddTicks(6876),
                            IsDeleted = false,
                            MailName = "داخي",
                            UpdatedDate = new DateTime(2020, 9, 13, 6, 10, 49, 600, DateTimeKind.Local).AddTicks(7774)
                        },
                        new
                        {
                            Id = 2,
                            InsertDate = new DateTime(2020, 9, 13, 6, 10, 49, 602, DateTimeKind.Local).AddTicks(8326),
                            IsDeleted = false,
                            MailName = "خارجي",
                            UpdatedDate = new DateTime(2020, 9, 13, 6, 10, 49, 602, DateTimeKind.Local).AddTicks(8344)
                        });
                });

            modelBuilder.Entity("Archieve.DatabaseLayer.Models.MangerDepartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsertUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("WorkPlaceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkPlaceId");

                    b.ToTable("MangerDepartment");
                });

            modelBuilder.Entity("Archieve.DatabaseLayer.Models.MilitaryRank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsertUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("RankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MilitaryRanks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InsertDate = new DateTime(2020, 9, 13, 6, 10, 49, 611, DateTimeKind.Local).AddTicks(2068),
                            IsDeleted = false,
                            RankName = "لواء ",
                            UpdatedDate = new DateTime(2020, 9, 13, 6, 10, 49, 611, DateTimeKind.Local).AddTicks(2088)
                        },
                        new
                        {
                            Id = 2,
                            InsertDate = new DateTime(2020, 9, 13, 6, 10, 49, 611, DateTimeKind.Local).AddTicks(2380),
                            IsDeleted = false,
                            RankName = " عميد",
                            UpdatedDate = new DateTime(2020, 9, 13, 6, 10, 49, 611, DateTimeKind.Local).AddTicks(2385)
                        },
                        new
                        {
                            Id = 3,
                            InsertDate = new DateTime(2020, 9, 13, 6, 10, 49, 611, DateTimeKind.Local).AddTicks(2403),
                            IsDeleted = false,
                            RankName = " عقيد",
                            UpdatedDate = new DateTime(2020, 9, 13, 6, 10, 49, 611, DateTimeKind.Local).AddTicks(2408)
                        },
                        new
                        {
                            Id = 4,
                            InsertDate = new DateTime(2020, 9, 13, 6, 10, 49, 611, DateTimeKind.Local).AddTicks(2421),
                            IsDeleted = false,
                            RankName = " مقدم",
                            UpdatedDate = new DateTime(2020, 9, 13, 6, 10, 49, 611, DateTimeKind.Local).AddTicks(2425)
                        },
                        new
                        {
                            Id = 5,
                            InsertDate = new DateTime(2020, 9, 13, 6, 10, 49, 611, DateTimeKind.Local).AddTicks(2437),
                            IsDeleted = false,
                            RankName = "رائد ",
                            UpdatedDate = new DateTime(2020, 9, 13, 6, 10, 49, 611, DateTimeKind.Local).AddTicks(2442)
                        },
                        new
                        {
                            Id = 6,
                            InsertDate = new DateTime(2020, 9, 13, 6, 10, 49, 611, DateTimeKind.Local).AddTicks(2458),
                            IsDeleted = false,
                            RankName = " نقيب",
                            UpdatedDate = new DateTime(2020, 9, 13, 6, 10, 49, 611, DateTimeKind.Local).AddTicks(2462)
                        },
                        new
                        {
                            Id = 7,
                            InsertDate = new DateTime(2020, 9, 13, 6, 10, 49, 611, DateTimeKind.Local).AddTicks(2474),
                            IsDeleted = false,
                            RankName = " ملازم اول",
                            UpdatedDate = new DateTime(2020, 9, 13, 6, 10, 49, 611, DateTimeKind.Local).AddTicks(2479)
                        },
                        new
                        {
                            Id = 8,
                            InsertDate = new DateTime(2020, 9, 13, 6, 10, 49, 611, DateTimeKind.Local).AddTicks(2490),
                            IsDeleted = false,
                            RankName = " ملازم",
                            UpdatedDate = new DateTime(2020, 9, 13, 6, 10, 49, 611, DateTimeKind.Local).AddTicks(2495)
                        },
                        new
                        {
                            Id = 9,
                            InsertDate = new DateTime(2020, 9, 13, 6, 10, 49, 611, DateTimeKind.Local).AddTicks(2506),
                            IsDeleted = false,
                            RankName = "مساعد اول ",
                            UpdatedDate = new DateTime(2020, 9, 13, 6, 10, 49, 611, DateTimeKind.Local).AddTicks(2511)
                        },
                        new
                        {
                            Id = 10,
                            InsertDate = new DateTime(2020, 9, 13, 6, 10, 49, 611, DateTimeKind.Local).AddTicks(2524),
                            IsDeleted = false,
                            RankName = " مساعد",
                            UpdatedDate = new DateTime(2020, 9, 13, 6, 10, 49, 611, DateTimeKind.Local).AddTicks(2529)
                        },
                        new
                        {
                            Id = 11,
                            InsertDate = new DateTime(2020, 9, 13, 6, 10, 49, 611, DateTimeKind.Local).AddTicks(2540),
                            IsDeleted = false,
                            RankName = " رقيب اول",
                            UpdatedDate = new DateTime(2020, 9, 13, 6, 10, 49, 611, DateTimeKind.Local).AddTicks(2544)
                        },
                        new
                        {
                            Id = 12,
                            InsertDate = new DateTime(2020, 9, 13, 6, 10, 49, 611, DateTimeKind.Local).AddTicks(2556),
                            IsDeleted = false,
                            RankName = " رقيب",
                            UpdatedDate = new DateTime(2020, 9, 13, 6, 10, 49, 611, DateTimeKind.Local).AddTicks(2561)
                        },
                        new
                        {
                            Id = 13,
                            InsertDate = new DateTime(2020, 9, 13, 6, 10, 49, 611, DateTimeKind.Local).AddTicks(2572),
                            IsDeleted = false,
                            RankName = "عريف ",
                            UpdatedDate = new DateTime(2020, 9, 13, 6, 10, 49, 611, DateTimeKind.Local).AddTicks(2577)
                        },
                        new
                        {
                            Id = 14,
                            InsertDate = new DateTime(2020, 9, 13, 6, 10, 49, 611, DateTimeKind.Local).AddTicks(2588),
                            IsDeleted = false,
                            RankName = " جندي",
                            UpdatedDate = new DateTime(2020, 9, 13, 6, 10, 49, 611, DateTimeKind.Local).AddTicks(2593)
                        },
                        new
                        {
                            Id = 15,
                            InsertDate = new DateTime(2020, 9, 13, 6, 10, 49, 611, DateTimeKind.Local).AddTicks(2604),
                            IsDeleted = false,
                            RankName = " عقد بطالة",
                            UpdatedDate = new DateTime(2020, 9, 13, 6, 10, 49, 611, DateTimeKind.Local).AddTicks(2609)
                        },
                        new
                        {
                            Id = 16,
                            InsertDate = new DateTime(2020, 9, 13, 6, 10, 49, 611, DateTimeKind.Local).AddTicks(2620),
                            IsDeleted = false,
                            RankName = " السيد",
                            UpdatedDate = new DateTime(2020, 9, 13, 6, 10, 49, 611, DateTimeKind.Local).AddTicks(2625)
                        });
                });

            modelBuilder.Entity("Archieve.DatabaseLayer.Models.PostType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsertUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PostName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PostTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InsertDate = new DateTime(2020, 9, 13, 6, 10, 49, 605, DateTimeKind.Local).AddTicks(4719),
                            IsDeleted = false,
                            PostName = "صادر",
                            UpdatedDate = new DateTime(2020, 9, 13, 6, 10, 49, 605, DateTimeKind.Local).AddTicks(4738)
                        },
                        new
                        {
                            Id = 2,
                            InsertDate = new DateTime(2020, 9, 13, 6, 10, 49, 605, DateTimeKind.Local).AddTicks(4976),
                            IsDeleted = false,
                            PostName = "وارد",
                            UpdatedDate = new DateTime(2020, 9, 13, 6, 10, 49, 605, DateTimeKind.Local).AddTicks(4981)
                        });
                });

            modelBuilder.Entity("Archieve.DatabaseLayer.Models.Security", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsertUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Securities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InsertDate = new DateTime(2020, 9, 13, 6, 10, 49, 603, DateTimeKind.Local).AddTicks(5515),
                            IsDeleted = false,
                            SecurityName = "عادي",
                            UpdatedDate = new DateTime(2020, 9, 13, 6, 10, 49, 603, DateTimeKind.Local).AddTicks(5537)
                        },
                        new
                        {
                            Id = 2,
                            InsertDate = new DateTime(2020, 9, 13, 6, 10, 49, 603, DateTimeKind.Local).AddTicks(5809),
                            IsDeleted = false,
                            SecurityName = "سري",
                            UpdatedDate = new DateTime(2020, 9, 13, 6, 10, 49, 603, DateTimeKind.Local).AddTicks(5815)
                        });
                });

            modelBuilder.Entity("Archieve.DatabaseLayer.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsertUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("StatusName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InsertDate = new DateTime(2020, 9, 13, 6, 10, 49, 606, DateTimeKind.Local).AddTicks(2825),
                            IsDeleted = false,
                            StatusName = "منجر",
                            UpdatedDate = new DateTime(2020, 9, 13, 6, 10, 49, 606, DateTimeKind.Local).AddTicks(2852)
                        },
                        new
                        {
                            Id = 2,
                            InsertDate = new DateTime(2020, 9, 13, 6, 10, 49, 606, DateTimeKind.Local).AddTicks(3212),
                            IsDeleted = false,
                            StatusName = "غير منجر",
                            UpdatedDate = new DateTime(2020, 9, 13, 6, 10, 49, 606, DateTimeKind.Local).AddTicks(3221)
                        });
                });

            modelBuilder.Entity("Archieve.DatabaseLayer.Models.StructureType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsertUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("StructureTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "الجهاز",
                            InsertDate = new DateTime(2020, 9, 13, 6, 10, 49, 609, DateTimeKind.Local).AddTicks(1590),
                            IsDeleted = false,
                            UpdatedDate = new DateTime(2020, 9, 13, 6, 10, 49, 609, DateTimeKind.Local).AddTicks(1611)
                        },
                        new
                        {
                            Id = 2,
                            Description = "الادارة",
                            InsertDate = new DateTime(2020, 9, 13, 6, 10, 49, 609, DateTimeKind.Local).AddTicks(1854),
                            IsDeleted = false,
                            UpdatedDate = new DateTime(2020, 9, 13, 6, 10, 49, 609, DateTimeKind.Local).AddTicks(1859)
                        },
                        new
                        {
                            Id = 3,
                            Description = "دائرة",
                            InsertDate = new DateTime(2020, 9, 13, 6, 10, 49, 609, DateTimeKind.Local).AddTicks(1877),
                            IsDeleted = false,
                            UpdatedDate = new DateTime(2020, 9, 13, 6, 10, 49, 609, DateTimeKind.Local).AddTicks(1882)
                        },
                        new
                        {
                            Id = 4,
                            Description = "قسم",
                            InsertDate = new DateTime(2020, 9, 13, 6, 10, 49, 609, DateTimeKind.Local).AddTicks(1894),
                            IsDeleted = false,
                            UpdatedDate = new DateTime(2020, 9, 13, 6, 10, 49, 609, DateTimeKind.Local).AddTicks(1899)
                        },
                        new
                        {
                            Id = 5,
                            Description = "وحدة",
                            InsertDate = new DateTime(2020, 9, 13, 6, 10, 49, 609, DateTimeKind.Local).AddTicks(1911),
                            IsDeleted = false,
                            UpdatedDate = new DateTime(2020, 9, 13, 6, 10, 49, 609, DateTimeKind.Local).AddTicks(1915)
                        },
                        new
                        {
                            Id = 6,
                            Description = "اخرى",
                            InsertDate = new DateTime(2020, 9, 13, 6, 10, 49, 609, DateTimeKind.Local).AddTicks(1933),
                            IsDeleted = false,
                            UpdatedDate = new DateTime(2020, 9, 13, 6, 10, 49, 609, DateTimeKind.Local).AddTicks(1937)
                        });
                });

            modelBuilder.Entity("Archieve.DatabaseLayer.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("FK_JehazId")
                        .HasColumnType("int");

                    b.Property<int>("FK_MilitaryRankId")
                        .HasColumnType("int");

                    b.Property<int>("FinanceNumber")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FourthName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdentityNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsertUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecondName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThirdName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("FK_JehazId");

                    b.HasIndex("FK_MilitaryRankId");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Archieve.DatabaseLayer.Models.WorkPlace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FK_WpId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsertUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FK_WpId");

                    b.ToTable("WorkPlaces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FK_WpId = 6,
                            InsertDate = new DateTime(2020, 9, 13, 6, 10, 49, 608, DateTimeKind.Local).AddTicks(999),
                            IsDeleted = false,
                            ParentId = 0,
                            Text = "عام",
                            UpdatedDate = new DateTime(2020, 9, 13, 6, 10, 49, 608, DateTimeKind.Local).AddTicks(1024)
                        },
                        new
                        {
                            Id = 2,
                            FK_WpId = 1,
                            InsertDate = new DateTime(2020, 9, 13, 6, 10, 49, 608, DateTimeKind.Local).AddTicks(1340),
                            IsDeleted = false,
                            ParentId = 1,
                            Text = "المديرية العامة للعمليات المركزية",
                            UpdatedDate = new DateTime(2020, 9, 13, 6, 10, 49, 608, DateTimeKind.Local).AddTicks(1345)
                        },
                        new
                        {
                            Id = 3,
                            FK_WpId = 6,
                            InsertDate = new DateTime(2020, 9, 13, 6, 10, 49, 608, DateTimeKind.Local).AddTicks(1363),
                            IsDeleted = false,
                            ParentId = 1,
                            Text = "هئيات خارجية",
                            UpdatedDate = new DateTime(2020, 9, 13, 6, 10, 49, 608, DateTimeKind.Local).AddTicks(1368)
                        },
                        new
                        {
                            Id = 4,
                            FK_WpId = 2,
                            InsertDate = new DateTime(2020, 9, 13, 6, 10, 49, 608, DateTimeKind.Local).AddTicks(1380),
                            IsDeleted = false,
                            ParentId = 2,
                            Text = "ادارة الاتصالات",
                            UpdatedDate = new DateTime(2020, 9, 13, 6, 10, 49, 608, DateTimeKind.Local).AddTicks(1384)
                        },
                        new
                        {
                            Id = 5,
                            FK_WpId = 3,
                            InsertDate = new DateTime(2020, 9, 13, 6, 10, 49, 608, DateTimeKind.Local).AddTicks(1463),
                            IsDeleted = false,
                            ParentId = 4,
                            Text = "دائرة نظم المعلومات",
                            UpdatedDate = new DateTime(2020, 9, 13, 6, 10, 49, 608, DateTimeKind.Local).AddTicks(1467)
                        },
                        new
                        {
                            Id = 6,
                            FK_WpId = 4,
                            InsertDate = new DateTime(2020, 9, 13, 6, 10, 49, 608, DateTimeKind.Local).AddTicks(1488),
                            IsDeleted = false,
                            ParentId = 5,
                            Text = "قسم البرمجة",
                            UpdatedDate = new DateTime(2020, 9, 13, 6, 10, 49, 608, DateTimeKind.Local).AddTicks(1492)
                        },
                        new
                        {
                            Id = 7,
                            FK_WpId = 2,
                            InsertDate = new DateTime(2020, 9, 13, 6, 10, 49, 608, DateTimeKind.Local).AddTicks(1505),
                            IsDeleted = false,
                            ParentId = 2,
                            Text = "ادارة الامداد",
                            UpdatedDate = new DateTime(2020, 9, 13, 6, 10, 49, 608, DateTimeKind.Local).AddTicks(1510)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Archieve.DatabaseLayer.Models.ImageArchive", b =>
                {
                    b.HasOne("Archieve.DatabaseLayer.Models.MailArchive", "MailArchive")
                        .WithMany("imageArchives")
                        .HasForeignKey("FK_MailArchiveID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Archieve.DatabaseLayer.Models.MailArchive", b =>
                {
                    b.HasOne("Archieve.DatabaseLayer.Models.Classification", "Classification")
                        .WithMany("mailArchives")
                        .HasForeignKey("FK_ClassificationId");

                    b.HasOne("Archieve.DatabaseLayer.Models.WorkPlace", "FromJehazId")
                        .WithMany("mailArchivesFrom")
                        .HasForeignKey("FK_FromJehazId");

                    b.HasOne("Archieve.DatabaseLayer.Models.MailType", "MailType")
                        .WithMany("mailArchives")
                        .HasForeignKey("FK_MailTypeId");

                    b.HasOne("Archieve.DatabaseLayer.Models.PostType", "PostType")
                        .WithMany("mailArchives")
                        .HasForeignKey("FK_PostTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Archieve.DatabaseLayer.Models.Security", "Security")
                        .WithMany("mailArchives")
                        .HasForeignKey("FK_SecurityId");

                    b.HasOne("Archieve.DatabaseLayer.Models.Status", "Status")
                        .WithMany("mailArchives")
                        .HasForeignKey("FK_StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Archieve.DatabaseLayer.Models.WorkPlace", "ToJehazId")
                        .WithMany("mailArchivesTo")
                        .HasForeignKey("FK_ToJehazId");

                    b.HasOne("Archieve.DatabaseLayer.Models.User", "user")
                        .WithMany("mailArchives")
                        .HasForeignKey("FK_User");

                    b.HasOne("Archieve.DatabaseLayer.Models.WorkPlace", "UserWorkPlace")
                        .WithMany()
                        .HasForeignKey("UserWorkPlaceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Archieve.DatabaseLayer.Models.MangerDepartment", b =>
                {
                    b.HasOne("Archieve.DatabaseLayer.Models.User", "User")
                        .WithMany("MangerDepartment")
                        .HasForeignKey("UserId");

                    b.HasOne("Archieve.DatabaseLayer.Models.WorkPlace", "WorkPlace")
                        .WithMany("MangerDepartment")
                        .HasForeignKey("WorkPlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Archieve.DatabaseLayer.Models.User", b =>
                {
                    b.HasOne("Archieve.DatabaseLayer.Models.WorkPlace", "WorkPlace")
                        .WithMany("Users")
                        .HasForeignKey("FK_JehazId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Archieve.DatabaseLayer.Models.MilitaryRank", "MilitaryRank")
                        .WithMany("users")
                        .HasForeignKey("FK_MilitaryRankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Archieve.DatabaseLayer.Models.WorkPlace", b =>
                {
                    b.HasOne("Archieve.DatabaseLayer.Models.StructureType", "StructureType")
                        .WithMany("workPlaces")
                        .HasForeignKey("FK_WpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Archieve.DatabaseLayer.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Archieve.DatabaseLayer.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Archieve.DatabaseLayer.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Archieve.DatabaseLayer.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
