// <auto-generated />
using System;
using Archieve.DataAccess.DataConfigration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Archieve.DataAccess.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200719070354_19_7_relationsfixing2")]
    partial class _19_7_relationsfixing2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Archieve.DatabaseLayer.Models.Classification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClassificationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsertUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Classifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassificationName = "ترقين قيد ",
                            InsertDate = new DateTime(2020, 7, 19, 10, 3, 52, 906, DateTimeKind.Local).AddTicks(1628),
                            IsDeleted = false,
                            UpdatedDate = new DateTime(2020, 7, 19, 10, 3, 52, 906, DateTimeKind.Local).AddTicks(2534)
                        },
                        new
                        {
                            Id = 2,
                            ClassificationName = " طلب اجازة",
                            InsertDate = new DateTime(2020, 7, 19, 10, 3, 52, 906, DateTimeKind.Local).AddTicks(3848),
                            IsDeleted = false,
                            UpdatedDate = new DateTime(2020, 7, 19, 10, 3, 52, 906, DateTimeKind.Local).AddTicks(3882)
                        },
                        new
                        {
                            Id = 3,
                            ClassificationName = " طلب صيانة",
                            InsertDate = new DateTime(2020, 7, 19, 10, 3, 52, 906, DateTimeKind.Local).AddTicks(3906),
                            IsDeleted = false,
                            UpdatedDate = new DateTime(2020, 7, 19, 10, 3, 52, 906, DateTimeKind.Local).AddTicks(3911)
                        },
                        new
                        {
                            Id = 4,
                            ClassificationName = " اوامر ادارية",
                            InsertDate = new DateTime(2020, 7, 19, 10, 3, 52, 906, DateTimeKind.Local).AddTicks(3920),
                            IsDeleted = false,
                            UpdatedDate = new DateTime(2020, 7, 19, 10, 3, 52, 906, DateTimeKind.Local).AddTicks(3926)
                        });
                });

            modelBuilder.Entity("Archieve.DatabaseLayer.Models.Employee", b =>
                {
                    b.Property<int>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FinID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsertUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmpId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Archieve.DatabaseLayer.Models.ImageArchive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("ContentMail")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Extension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FK_MailArchiveID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsertUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeletedd")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FK_MailArchiveID");

                    b.ToTable("ImageArchives");
                });

            modelBuilder.Entity("Archieve.DatabaseLayer.Models.MailArchive", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("ArchiveDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FK_ClassificationId")
                        .HasColumnType("int");

                    b.Property<int?>("FK_MailTypeId")
                        .HasColumnType("int");

                    b.Property<int>("FK_PostTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("FK_SecurityId")
                        .HasColumnType("int");

                    b.Property<int>("FK_StatusId")
                        .HasColumnType("int");

                    b.Property<string>("FK_User")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsertUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MailId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Topic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WorkPlaceId")
                        .HasColumnType("int");

                    b.Property<int?>("WorkPlaceId1")
                        .HasColumnType("int");

                    b.Property<string>("Year")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("FK_ClassificationId");

                    b.HasIndex("FK_MailTypeId");

                    b.HasIndex("FK_PostTypeId");

                    b.HasIndex("FK_SecurityId");

                    b.HasIndex("FK_StatusId");

                    b.HasIndex("FK_User");

                    b.HasIndex("WorkPlaceId");

                    b.HasIndex("WorkPlaceId1");

                    b.ToTable("MailArchives");
                });

            modelBuilder.Entity("Archieve.DatabaseLayer.Models.MailType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsertUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MailName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MailTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InsertDate = new DateTime(2020, 7, 19, 10, 3, 52, 895, DateTimeKind.Local).AddTicks(7683),
                            IsDeleted = false,
                            MailName = "داخي",
                            UpdatedDate = new DateTime(2020, 7, 19, 10, 3, 52, 901, DateTimeKind.Local).AddTicks(6174)
                        },
                        new
                        {
                            Id = 2,
                            InsertDate = new DateTime(2020, 7, 19, 10, 3, 52, 903, DateTimeKind.Local).AddTicks(8060),
                            IsDeleted = false,
                            MailName = "خارجي",
                            UpdatedDate = new DateTime(2020, 7, 19, 10, 3, 52, 903, DateTimeKind.Local).AddTicks(8147)
                        });
                });

            modelBuilder.Entity("Archieve.DatabaseLayer.Models.PostType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsertUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PostName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PostTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InsertDate = new DateTime(2020, 7, 19, 10, 3, 52, 907, DateTimeKind.Local).AddTicks(3742),
                            IsDeleted = false,
                            PostName = "صادر",
                            UpdatedDate = new DateTime(2020, 7, 19, 10, 3, 52, 907, DateTimeKind.Local).AddTicks(4776)
                        },
                        new
                        {
                            Id = 2,
                            InsertDate = new DateTime(2020, 7, 19, 10, 3, 52, 907, DateTimeKind.Local).AddTicks(8814),
                            IsDeleted = false,
                            PostName = "وارد",
                            UpdatedDate = new DateTime(2020, 7, 19, 10, 3, 52, 907, DateTimeKind.Local).AddTicks(8859)
                        });
                });

            modelBuilder.Entity("Archieve.DatabaseLayer.Models.Security", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsertUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Securities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InsertDate = new DateTime(2020, 7, 19, 10, 3, 52, 904, DateTimeKind.Local).AddTicks(7341),
                            IsDeleted = false,
                            SecurityName = "عادي",
                            UpdatedDate = new DateTime(2020, 7, 19, 10, 3, 52, 904, DateTimeKind.Local).AddTicks(8390)
                        },
                        new
                        {
                            Id = 2,
                            InsertDate = new DateTime(2020, 7, 19, 10, 3, 52, 904, DateTimeKind.Local).AddTicks(9910),
                            IsDeleted = false,
                            SecurityName = "سري",
                            UpdatedDate = new DateTime(2020, 7, 19, 10, 3, 52, 904, DateTimeKind.Local).AddTicks(9958)
                        });
                });

            modelBuilder.Entity("Archieve.DatabaseLayer.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsertUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("StatusName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InsertDate = new DateTime(2020, 7, 19, 10, 3, 52, 908, DateTimeKind.Local).AddTicks(8355),
                            IsDeleted = false,
                            StatusName = "منجر",
                            UpdatedDate = new DateTime(2020, 7, 19, 10, 3, 52, 908, DateTimeKind.Local).AddTicks(9278)
                        },
                        new
                        {
                            Id = 2,
                            InsertDate = new DateTime(2020, 7, 19, 10, 3, 52, 909, DateTimeKind.Local).AddTicks(690),
                            IsDeleted = false,
                            StatusName = "غير منجر",
                            UpdatedDate = new DateTime(2020, 7, 19, 10, 3, 52, 909, DateTimeKind.Local).AddTicks(728)
                        });
                });

            modelBuilder.Entity("Archieve.DatabaseLayer.Models.StructureType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsertUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeletedd")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StructureTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "الجهاز",
                            InsertDate = new DateTime(2020, 7, 19, 10, 3, 52, 912, DateTimeKind.Local).AddTicks(9844),
                            IsDeletedd = false,
                            UpdatedDate = new DateTime(2020, 7, 19, 10, 3, 52, 913, DateTimeKind.Local).AddTicks(737)
                        },
                        new
                        {
                            Id = 2,
                            Description = "الادارة",
                            InsertDate = new DateTime(2020, 7, 19, 10, 3, 52, 913, DateTimeKind.Local).AddTicks(1965),
                            IsDeletedd = false,
                            UpdatedDate = new DateTime(2020, 7, 19, 10, 3, 52, 913, DateTimeKind.Local).AddTicks(1993)
                        },
                        new
                        {
                            Id = 3,
                            Description = "دائرة",
                            InsertDate = new DateTime(2020, 7, 19, 10, 3, 52, 913, DateTimeKind.Local).AddTicks(2016),
                            IsDeletedd = false,
                            UpdatedDate = new DateTime(2020, 7, 19, 10, 3, 52, 913, DateTimeKind.Local).AddTicks(2022)
                        },
                        new
                        {
                            Id = 4,
                            Description = "قسم",
                            InsertDate = new DateTime(2020, 7, 19, 10, 3, 52, 913, DateTimeKind.Local).AddTicks(2031),
                            IsDeletedd = false,
                            UpdatedDate = new DateTime(2020, 7, 19, 10, 3, 52, 913, DateTimeKind.Local).AddTicks(2036)
                        },
                        new
                        {
                            Id = 5,
                            Description = "وحدة",
                            InsertDate = new DateTime(2020, 7, 19, 10, 3, 52, 913, DateTimeKind.Local).AddTicks(2044),
                            IsDeletedd = false,
                            UpdatedDate = new DateTime(2020, 7, 19, 10, 3, 52, 913, DateTimeKind.Local).AddTicks(2049)
                        },
                        new
                        {
                            Id = 6,
                            Description = "اخرى",
                            InsertDate = new DateTime(2020, 7, 19, 10, 3, 52, 913, DateTimeKind.Local).AddTicks(2063),
                            IsDeletedd = false,
                            UpdatedDate = new DateTime(2020, 7, 19, 10, 3, 52, 913, DateTimeKind.Local).AddTicks(2068)
                        });
                });

            modelBuilder.Entity("Archieve.DatabaseLayer.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("FK_JehazId")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("FK_JehazId");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Archieve.DatabaseLayer.Models.WorkPlace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FK_WpId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsertUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeletedd")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FK_WpId");

                    b.ToTable("WorkPlaces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FK_WpId = 6,
                            InsertDate = new DateTime(2020, 7, 19, 10, 3, 52, 911, DateTimeKind.Local).AddTicks(4439),
                            IsDeletedd = false,
                            ParentId = 0,
                            Text = "عام",
                            UpdatedDate = new DateTime(2020, 7, 19, 10, 3, 52, 911, DateTimeKind.Local).AddTicks(5365)
                        },
                        new
                        {
                            Id = 2,
                            FK_WpId = 1,
                            InsertDate = new DateTime(2020, 7, 19, 10, 3, 52, 911, DateTimeKind.Local).AddTicks(6639),
                            IsDeletedd = false,
                            ParentId = 1,
                            Text = "المديرية العامة للعمليات المركزية",
                            UpdatedDate = new DateTime(2020, 7, 19, 10, 3, 52, 911, DateTimeKind.Local).AddTicks(6671)
                        },
                        new
                        {
                            Id = 3,
                            FK_WpId = 6,
                            InsertDate = new DateTime(2020, 7, 19, 10, 3, 52, 911, DateTimeKind.Local).AddTicks(6698),
                            IsDeletedd = false,
                            ParentId = 1,
                            Text = "هئيات خارجية",
                            UpdatedDate = new DateTime(2020, 7, 19, 10, 3, 52, 911, DateTimeKind.Local).AddTicks(6704)
                        },
                        new
                        {
                            Id = 4,
                            FK_WpId = 2,
                            InsertDate = new DateTime(2020, 7, 19, 10, 3, 52, 911, DateTimeKind.Local).AddTicks(6714),
                            IsDeletedd = false,
                            ParentId = 2,
                            Text = "ادارة الاتصالات",
                            UpdatedDate = new DateTime(2020, 7, 19, 10, 3, 52, 911, DateTimeKind.Local).AddTicks(6719)
                        },
                        new
                        {
                            Id = 5,
                            FK_WpId = 3,
                            InsertDate = new DateTime(2020, 7, 19, 10, 3, 52, 911, DateTimeKind.Local).AddTicks(6728),
                            IsDeletedd = false,
                            ParentId = 4,
                            Text = "دائرة نظم المعلومات",
                            UpdatedDate = new DateTime(2020, 7, 19, 10, 3, 52, 911, DateTimeKind.Local).AddTicks(6733)
                        },
                        new
                        {
                            Id = 6,
                            FK_WpId = 4,
                            InsertDate = new DateTime(2020, 7, 19, 10, 3, 52, 911, DateTimeKind.Local).AddTicks(6747),
                            IsDeletedd = false,
                            ParentId = 5,
                            Text = "قسم البرمجة",
                            UpdatedDate = new DateTime(2020, 7, 19, 10, 3, 52, 911, DateTimeKind.Local).AddTicks(6752)
                        },
                        new
                        {
                            Id = 7,
                            FK_WpId = 2,
                            InsertDate = new DateTime(2020, 7, 19, 10, 3, 52, 911, DateTimeKind.Local).AddTicks(6760),
                            IsDeletedd = false,
                            ParentId = 2,
                            Text = "ادارة الامداد",
                            UpdatedDate = new DateTime(2020, 7, 19, 10, 3, 52, 911, DateTimeKind.Local).AddTicks(6766)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Archieve.DatabaseLayer.Models.ImageArchive", b =>
                {
                    b.HasOne("Archieve.DatabaseLayer.Models.MailArchive", "MailArchive")
                        .WithMany("imageArchives")
                        .HasForeignKey("FK_MailArchiveID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Archieve.DatabaseLayer.Models.MailArchive", b =>
                {
                    b.HasOne("Archieve.DatabaseLayer.Models.Classification", "Classification")
                        .WithMany("mailArchives")
                        .HasForeignKey("FK_ClassificationId");

                    b.HasOne("Archieve.DatabaseLayer.Models.MailType", "MailType")
                        .WithMany("mailArchives")
                        .HasForeignKey("FK_MailTypeId");

                    b.HasOne("Archieve.DatabaseLayer.Models.PostType", "PostType")
                        .WithMany("mailArchives")
                        .HasForeignKey("FK_PostTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Archieve.DatabaseLayer.Models.Security", "Security")
                        .WithMany("mailArchives")
                        .HasForeignKey("FK_SecurityId");

                    b.HasOne("Archieve.DatabaseLayer.Models.Status", "Status")
                        .WithMany("mailArchives")
                        .HasForeignKey("FK_StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Archieve.DatabaseLayer.Models.User", "user")
                        .WithMany("mailArchives")
                        .HasForeignKey("FK_User");

                    b.HasOne("Archieve.DatabaseLayer.Models.WorkPlace", null)
                        .WithMany("mailArchives")
                        .HasForeignKey("WorkPlaceId");

                    b.HasOne("Archieve.DatabaseLayer.Models.WorkPlace", null)
                        .WithMany("mailArchivesto")
                        .HasForeignKey("WorkPlaceId1");
                });

            modelBuilder.Entity("Archieve.DatabaseLayer.Models.User", b =>
                {
                    b.HasOne("Archieve.DatabaseLayer.Models.WorkPlace", "WorkPlace")
                        .WithMany("Users")
                        .HasForeignKey("FK_JehazId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Archieve.DatabaseLayer.Models.WorkPlace", b =>
                {
                    b.HasOne("Archieve.DatabaseLayer.Models.StructureType", "StructureType")
                        .WithMany("workPlaces")
                        .HasForeignKey("FK_WpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Archieve.DatabaseLayer.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Archieve.DatabaseLayer.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Archieve.DatabaseLayer.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Archieve.DatabaseLayer.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
